class ContagemImpressoras:
    def __init__(self, ID, IMPRESSORA_ID, CONTADOR_PB, CONTADOR_COR, CONTADOR_TOTAL, DATA_LEITURA, CREATED_AT):
        self.ID = ID
        self.IMPRESSORA_ID = IMPRESSORA_ID
        self.CONTADOR_PB = CONTADOR_PB
        self.CONTADOR_COR = CONTADOR_COR
        self.CONTADOR_TOTAL = CONTADOR_TOTAL
        self.DATA_LEITURA = DATA_LEITURA
        self.CREATED_AT = CREATED_AT

class Impressoras:
    def __init__(self, ID, PRINTERDEVICEID, PRINTERBRANDNAME, PRINTERMODELNAME, SERIALNUMBER, CREATED_AT, STATUS):
        self.ID = ID
        self.PRINTERDEVICEID = PRINTERDEVICEID
        self.PRINTERBRANDNAME = PRINTERBRANDNAME
        self.PRINTERMODELNAME = PRINTERMODELNAME
        self.SERIALNUMBER = SERIALNUMBER
        self.CREATED_AT = CREATED_AT
        self.STATUS = STATUS
